### ISSUE TITLE
Unable to build firmware when using NERVES_SYSTEM_CACHE=local

### ISSUE THREAD

**Issue by wsmoak** [nerves-project/nerves_system#1]
Using nerves_system 0.1.3 with with `NERVES_SYSTEM_CACHE=local`

```
$ mix nerves.new delete_me --target rpi2
$ cd delete_me/
$ mix deps.get
$ mix compile
$ mix firmware
** (Nerves.Env.Exception) ERROR: It looks like the system hasn't been built!
```

full output here: https://gist.github.com/wsmoak/343a47cf100c110892d263f311e9b30c

Elixir 1.2.5
Erlang/OTP 18 [erts-7.2.1]
Nerves v0.1.2 (from mix nerves.new --version)
mix.lock shows nerves 0.3.1

If I switch back to `NERVES_SYSTEM_CACHE=http` and repeat the steps, it works fine.

**Comment by wsmoak** [comment]
As a workaround, if you run all the steps in one invocation of Mix, it seems to work:
```
rm -rf _build
rm -rf _images
mix do deps.get, compile, firmware, firmware.burn
```

**Comment by mobileoverlord** [comment]
The issue here is that when using local cache `NERVES_SYSTEM

**Comment by mobileoverlord** [comment]
fixes for this have been moved into `nerves` as this package is getting deprecated
