### ISSUE TITLE
README needs to be updated

### ISSUE THREAD

**Issue by GregMefford** [nerves-project/nerves_system#3]
It looks like the content of the README is describing the details of `nerves_system_br`. For example, it refers to included `defconfigs`, which aren't stored here. I think this particular repository should give an overview of what a Nerves System is, how they're built, how they integrate with Mix, and refer to more details in other repositories.

**Comment by mobileoverlord** [comment]
This package is going to be deprecated and the readme will be changed to redirect people to `:nerves`
