### ISSUE TITLE
** (Nerves.Env.Exception) Major version mismatch between host and target Erlang/OTP versions   Host version: 18   Target version: 19

### ISSUE THREAD

**Issue by jasmo2** [nerves-project/nerves_system#6]
now that the new OTP version is available my computer has not get it yet.

¿How Do I tell on the compile to take OTP version 18?

**Comment by fhunleth** [comment]
We supply the OTP versions for the target hardware (Raspberry Pi, Beaglebone, etc.). Currently we are only supporting OTP 19. You'll need to update your version of Erlang. I use the versions at https://www.erlang-solutions.com/resources/download.html. Hopefully they have one for your computer.
